package admin;

import conexao.Conexao;
import controle.login;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author werlang
 */
public class frm_pre_gporteiros extends javax.swing.JFrame {

    private int idConSelecionado;

    /**
     * @return the idConSelecionado
     */
    public int getIdConSelecionado() {
        return idConSelecionado;
    }

    /**
     * @param idConSelecionado the idConSelecionado to set
     */
    public void setIdConSelecionado(int idConSelecionado) {
        this.idConSelecionado = idConSelecionado;
    }

    private String tipoTela;
    

    //Objeto com atributos da classe Connection. Finalidade: Ligação com Banco de Dados.
    Connection con = null;
    
    //Objeto com atributos da classe ResultSet. Finalidade: Procura dos registros do banco.
    ResultSet rs = null;
    
    /*Objeto com atributos da classe PreparedStatement. 
    Finalidade: Adicionar os dados inseridos pelo usuário na busca de dados do banco.*/
    PreparedStatement ps = null;
    
    
    /**
     * Creates new form frm_pre_gporteiros
     */
    public frm_pre_gporteiros(String tipoTelaPort) {
        initComponents();
        con = Conexao.conecta();
        preReq(tipoTelaPort);
        logo();
        definirCor();
        atualizarComboBox();
    }
    
    //Método initVars() responsável por passar parâmetros de dados do usuário e
    //adicioná-los em atributos locais (da classe):
    private void preReq(String tipoTelaPort)
    {
        tipoTela = tipoTelaPort;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back1 = new javax.swing.JPanel();
        back2 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btn_home = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        back3 = new javax.swing.JPanel();
        back4 = new javax.swing.JPanel();
        jcb_condominio = new javax.swing.JComboBox<>();
        lbl_desc = new javax.swing.JLabel();
        btn_Avancar = new javax.swing.JButton();
        btn_cond_in = new javax.swing.JButton();
        btn_port_in = new javax.swing.JButton();
        btn_gerenc_cond = new javax.swing.JButton();
        btn_gerenc_port = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        back1.setBackground(new java.awt.Color(11, 25, 49));

        back2.setBackground(new java.awt.Color(11, 25, 49));

        btn_home.setBackground(new java.awt.Color(51, 121, 241));
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button/home.png"))); // NOI18N
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        btn_exit.setBackground(new java.awt.Color(51, 121, 241));
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button/exit.png"))); // NOI18N
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout back2Layout = new javax.swing.GroupLayout(back2);
        back2.setLayout(back2Layout);
        back2Layout.setHorizontalGroup(
            back2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(back2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        back2Layout.setVerticalGroup(
            back2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, back2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(back2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addGroup(back2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(back2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        back3.setBackground(new java.awt.Color(212, 223, 253));

        back4.setBackground(new java.awt.Color(255, 255, 255));
        back4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 25, 49)));

        jcb_condominio.setEditable(true);
        jcb_condominio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lbl_desc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_desc.setForeground(new java.awt.Color(11, 25, 49));
        lbl_desc.setText("SELECIONE UM CONDOMÍNIO");

        btn_Avancar.setBackground(new java.awt.Color(51, 121, 241));
        btn_Avancar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Avancar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Avancar.setText("Avançar");
        btn_Avancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AvancarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout back4Layout = new javax.swing.GroupLayout(back4);
        back4.setLayout(back4Layout);
        back4Layout.setHorizontalGroup(
            back4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(back4Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(back4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(back4Layout.createSequentialGroup()
                        .addComponent(jcb_condominio, 0, 417, Short.MAX_VALUE)
                        .addGap(113, 113, 113))
                    .addGroup(back4Layout.createSequentialGroup()
                        .addGroup(back4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_desc)
                            .addComponent(btn_Avancar, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        back4Layout.setVerticalGroup(
            back4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(back4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbl_desc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcb_condominio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(btn_Avancar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout back3Layout = new javax.swing.GroupLayout(back3);
        back3.setLayout(back3Layout);
        back3Layout.setHorizontalGroup(
            back3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(back3Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(back4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(164, 164, 164))
        );
        back3Layout.setVerticalGroup(
            back3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(back3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(back4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(68, 68, 68))
        );

        btn_cond_in.setBackground(new java.awt.Color(51, 121, 241));
        btn_cond_in.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_cond_in.setForeground(new java.awt.Color(255, 255, 255));
        btn_cond_in.setText("<html> \n<center> \nCondomínios <br/> Inativados\n</center>\n</html>\n");
        btn_cond_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cond_inActionPerformed(evt);
            }
        });

        btn_port_in.setBackground(new java.awt.Color(51, 121, 241));
        btn_port_in.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_port_in.setForeground(new java.awt.Color(255, 255, 255));
        btn_port_in.setText("<html> \n<center> \nPorteiros <br/> Inativados\n</center>\n</html>");
        btn_port_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_port_inActionPerformed(evt);
            }
        });

        btn_gerenc_cond.setBackground(new java.awt.Color(51, 121, 241));
        btn_gerenc_cond.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_gerenc_cond.setForeground(new java.awt.Color(255, 255, 255));
        btn_gerenc_cond.setText("<html>  \n<center>  \nGerenciamento <br/> de Condomínios \n</center> \n</html>");
        btn_gerenc_cond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gerenc_condActionPerformed(evt);
            }
        });

        btn_gerenc_port.setBackground(new java.awt.Color(51, 121, 241));
        btn_gerenc_port.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_gerenc_port.setForeground(new java.awt.Color(255, 255, 255));
        btn_gerenc_port.setText("<html>  \n<center>  \nGerenciamento <br/> dos Porteiros \n</center> \n</html>\n");
        btn_gerenc_port.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gerenc_portActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout back1Layout = new javax.swing.GroupLayout(back1);
        back1.setLayout(back1Layout);
        back1Layout.setHorizontalGroup(
            back1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, back1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(back1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(back1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_cond_in, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                        .addComponent(btn_port_in))
                    .addComponent(btn_gerenc_cond, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_gerenc_port, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(back3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        back1Layout.setVerticalGroup(
            back1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(back1Layout.createSequentialGroup()
                .addComponent(back2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(back1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(back1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(back3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(back1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btn_gerenc_cond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btn_gerenc_port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btn_cond_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btn_port_in, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_gerenc_condActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gerenc_condActionPerformed
        frm_gerenc_condominio mostra = new frm_gerenc_condominio();
        mostra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_gerenc_condActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        login mostra = new login();
        mostra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_port_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_port_inActionPerformed
        String tipoTelaPort = "inativos";
        frm_pre_gporteiros mostra = new frm_pre_gporteiros(tipoTelaPort);
        mostra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_port_inActionPerformed

    private void btn_cond_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cond_inActionPerformed
        frm_cond_inativos mostra = new frm_cond_inativos();
        mostra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_cond_inActionPerformed

    private void btn_gerenc_portActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gerenc_portActionPerformed
        String tipoTelaPort = "ativos";
        frm_pre_gporteiros mostra = new frm_pre_gporteiros(tipoTelaPort);
        mostra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_gerenc_portActionPerformed

    private void btn_AvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AvancarActionPerformed
        
        String selectedItem = (String) jcb_condominio.getSelectedItem();
        
        if (selectedItem != null) 
        {
        String[] parts = selectedItem.split(" - ");
            if (parts.length == 2)
            {
                String nomeCondominio = parts[0];
                String cnpj = parts[1];
                
                try {
                    String pesquisaIdMorador = "SELECT id_condominio FROM condominio WHERE nome_condominio = ? AND cnpj = ?";
                    ps = con.prepareStatement(pesquisaIdMorador);
                    ps.setString(1, nomeCondominio);
                    ps.setString(2, cnpj);

                    rs = ps.executeQuery();
                    if (rs.next()) {
                        int idCond = rs.getInt("id_condominio");
                        setIdConSelecionado(idCond);
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Não foi possível obter os dados requisitados!", "Mensagem do Programa", JOptionPane.ERROR_MESSAGE);
                }

            } 
            else 
            {
                JOptionPane.showMessageDialog(null, "Não foi possível obter os dados requisitados!", "Mensagem do Programa", JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Por favor, selecione um condomínio para acessar o serviço desejado!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
        
        if("ativos".equals(tipoTela)){
            frm_gerenc_porteiros mostra = new frm_gerenc_porteiros(getIdConSelecionado());
            mostra.setVisible(true);
            dispose();
        }
        else{
            frm_port_inativos mostra = new frm_port_inativos(getIdConSelecionado());
            mostra.setVisible(true);
            dispose();
        }
        
    }//GEN-LAST:event_btn_AvancarActionPerformed

    private void logo(){
            ImageIcon imageIcon = new ImageIcon(getClass().getResource("/img/logo/SRs.png"));
            Image scaleImage = imageIcon.getImage().getScaledInstance(170, 170,Image.SCALE_DEFAULT);
            ImageIcon img = new ImageIcon(scaleImage);
            lblLogo.setIcon(img);
    }

    private void atualizarComboBox(){
        String pesquisa = "SELECT * FROM condominio";
        try 
        {
            ps = con.prepareStatement(pesquisa);
            rs = ps.executeQuery();

            while (rs.next()) {
                jcb_condominio.addItem(rs.getString("nome_condominio") + " - " + rs.getString("cnpj"));
            }
        }
        catch (SQLException e) 
        {
            JOptionPane.showMessageDialog(null, "A listagem de dados falhou!", "Mensagem do Programa", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void definirCor(){
        if(tipoTela == "ativos"){
            btn_gerenc_port.setBackground(new Color(0,53,143));
            btn_port_in.setBackground(new Color(51,121,241));
        }
        else{
            btn_port_in.setBackground(new Color(0,53,143));
            btn_gerenc_port.setBackground(new Color(51,121,241));            
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel back1;
    private javax.swing.JPanel back2;
    private javax.swing.JPanel back3;
    private javax.swing.JPanel back4;
    private javax.swing.JButton btn_Avancar;
    private javax.swing.JButton btn_cond_in;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_gerenc_cond;
    private javax.swing.JButton btn_gerenc_port;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_port_in;
    private javax.swing.JComboBox<String> jcb_condominio;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lbl_desc;
    // End of variables declaration//GEN-END:variables
}
