/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import conexao.Conexao;
import controle.login;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import porteiro.frm_menu_porteiro;

/**
 *
 * @author werlang
 */
public class frm_port_inativos extends javax.swing.JFrame {

    private int id_cond;
    
    
    //Objeto com atributos da classe Connection. Finalidade: Ligação com Banco de Dados.
    Connection con = null;
    
    //Objeto com atributos da classe ResultSet. Finalidade: Procura dos registros do banco.
    ResultSet rs = null;
    
    /*Objeto com atributos da classe PreparedStatement. 
    Finalidade: Adicionar os dados inseridos pelo usuário na busca de dados do banco.*/
    PreparedStatement ps = null;
    
    /**
     * Creates new form frm_port_inativos
     */
    public frm_port_inativos(int realId) {
        initComponents();
        con = Conexao.conecta();
        initVars(realId);
        logo();
        try 
        {
            String pesquisa = "SELECT usuario.nome, usuario.num_acesso, usuario.senha, porteiro.turno " +
                    "FROM porteiro " +
                    "INNER JOIN usuario ON porteiro.id_usuario = usuario.id_usuario " +
                    "WHERE usuario.situacao = 'inativo' AND porteiro.id_condominio = ? " +
                    "ORDER BY id_condominio";
            ps = con.prepareStatement(pesquisa);
            ps.setInt(1, id_cond);
            rs = ps.executeQuery();
        } 
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(null, "Dados não localizados!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
        preencherTabela();

    }
    
    //Método initVars() responsável por passar parâmetros de dados do usuário e
    //adicioná-los em atributos locais (da classe):
    private void initVars(int realId)
    {
        id_cond = realId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back1 = new javax.swing.JPanel();
        back2 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        btn_home = new javax.swing.JButton();
        back3 = new javax.swing.JPanel();
        btn_Reativar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_port_inativados = new javax.swing.JTable();
        lbl_Titulo = new javax.swing.JLabel();
        lbl_desc = new javax.swing.JLabel();
        btn_gerenc_cond = new javax.swing.JButton();
        btn_gerenc_port = new javax.swing.JButton();
        btn_cond_in = new javax.swing.JButton();
        btn_port_in = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        back1.setBackground(new java.awt.Color(11, 25, 49));

        back2.setBackground(new java.awt.Color(11, 25, 49));

        btn_exit.setBackground(new java.awt.Color(51, 121, 241));
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button/exit.png"))); // NOI18N
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        btn_home.setBackground(new java.awt.Color(51, 121, 241));
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button/home.png"))); // NOI18N
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout back2Layout = new javax.swing.GroupLayout(back2);
        back2.setLayout(back2Layout);
        back2Layout.setHorizontalGroup(
            back2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(back2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        back2Layout.setVerticalGroup(
            back2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, back2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(back2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(back2Layout.createSequentialGroup()
                        .addGap(0, 147, Short.MAX_VALUE)
                        .addGroup(back2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        back3.setBackground(new java.awt.Color(212, 223, 253));

        btn_Reativar.setBackground(new java.awt.Color(51, 121, 241));
        btn_Reativar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Reativar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Reativar.setText("Reativar Porteiro");
        btn_Reativar.setEnabled(false);
        btn_Reativar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReativarActionPerformed(evt);
            }
        });

        tbl_port_inativados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Número de Acesso", "Senha", "Turno"
            }
        ));
        tbl_port_inativados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_port_inativadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_port_inativados);

        lbl_Titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_Titulo.setForeground(new java.awt.Color(11, 25, 49));
        lbl_Titulo.setText("PORTEIROS INATIVADOS\n");

        lbl_desc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_desc.setForeground(new java.awt.Color(11, 25, 49));
        lbl_desc.setText("Selecione o porteiro para reativá-lo\n");

        javax.swing.GroupLayout back3Layout = new javax.swing.GroupLayout(back3);
        back3.setLayout(back3Layout);
        back3Layout.setHorizontalGroup(
            back3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(back3Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(back3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_desc)
                    .addComponent(lbl_Titulo)
                    .addComponent(btn_Reativar, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE))
                .addGap(164, 164, 164))
        );
        back3Layout.setVerticalGroup(
            back3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(back3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lbl_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_desc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Reativar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        btn_gerenc_cond.setBackground(new java.awt.Color(51, 121, 241));
        btn_gerenc_cond.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_gerenc_cond.setForeground(new java.awt.Color(255, 255, 255));
        btn_gerenc_cond.setText("<html>  \n<center>  \nGerenciamento <br/> de Condomínios \n</center> \n</html>\n");
        btn_gerenc_cond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gerenc_condActionPerformed(evt);
            }
        });

        btn_gerenc_port.setBackground(new java.awt.Color(51, 121, 241));
        btn_gerenc_port.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_gerenc_port.setForeground(new java.awt.Color(255, 255, 255));
        btn_gerenc_port.setText("<html>  \n<center>  \nGerenciamento <br/> dos Porteiros \n</center> \n</html>");
        btn_gerenc_port.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gerenc_portActionPerformed(evt);
            }
        });

        btn_cond_in.setBackground(new java.awt.Color(51, 121, 241));
        btn_cond_in.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_cond_in.setForeground(new java.awt.Color(255, 255, 255));
        btn_cond_in.setText("<html> \n<center> \nCondomínios <br/> Inativados\n</center>\n</html>");
        btn_cond_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cond_inActionPerformed(evt);
            }
        });

        btn_port_in.setBackground(new java.awt.Color(0, 53, 143));
        btn_port_in.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_port_in.setForeground(new java.awt.Color(255, 255, 255));
        btn_port_in.setText("<html> \n<center> \nPorteiros <br/> Inativados\n</center>\n</html>");
        btn_port_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_port_inActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout back1Layout = new javax.swing.GroupLayout(back1);
        back1.setLayout(back1Layout);
        back1Layout.setHorizontalGroup(
            back1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(back1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(back1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_gerenc_cond, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_gerenc_port, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cond_in, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_port_in, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(back3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        back1Layout.setVerticalGroup(
            back1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(back1Layout.createSequentialGroup()
                .addComponent(back2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(back1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(back1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(back3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(back1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btn_gerenc_cond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btn_gerenc_port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btn_cond_in, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btn_port_in, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_gerenc_portActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gerenc_portActionPerformed
        String tipoTelaPort = "ativos";
        frm_pre_gporteiros mostra = new frm_pre_gporteiros(tipoTelaPort);
        mostra.setVisible(true);
        dispose();        
    }//GEN-LAST:event_btn_gerenc_portActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        login mostra = new login();
        mostra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_gerenc_condActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gerenc_condActionPerformed
        frm_gerenc_condominio mostra = new frm_gerenc_condominio();
        mostra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_gerenc_condActionPerformed

    private void btn_cond_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cond_inActionPerformed
        frm_cond_inativos mostra = new frm_cond_inativos();
        mostra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_cond_inActionPerformed

    private void btn_port_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_port_inActionPerformed
        String tipoTelaPort = "inativos";
        frm_pre_gporteiros mostra = new frm_pre_gporteiros(tipoTelaPort);
        mostra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_port_inActionPerformed

    private void tbl_port_inativadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_port_inativadosMouseClicked
        btn_Reativar.setEnabled(true);
    }//GEN-LAST:event_tbl_port_inativadosMouseClicked

    private void btn_ReativarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReativarActionPerformed
        
        //Permitindo a seleção de um registro da tabela:
        tbl_port_inativados.setRowSelectionAllowed(true);
        
        //Armazenando a linha do registro selecionado em um atributo:
        int linha_selecionada = tbl_port_inativados.getSelectedRow();
        
        //Armazenando o valor do cnpj do registro selecionado:
        String num_acesso = tbl_port_inativados.getValueAt(linha_selecionada, 1).toString();
        
        //Verificando se um registro foi realmente selecionado:
        if (linha_selecionada >= 0) {                       
            
            //Declarando atributo que será utilizado para reativar um registro no comando sql
            String situacao = "ativo";        
            //Atributo que armazenará o comando sql
            String sql= "";
            //Atributo que armazerá uma descrição da ação que está ocorrendo
            String msg= "";

            try
            {
                //Comando SQL:
                String pesquisa = "SELECT * FROM usuario WHERE num_acesso=?";
                /*Comando que "prepara" declaração para busca no banco, onde os dados 
                inseridos serão colocados no lugar do '?' de cada campo do select*/
                ps = con.prepareStatement(pesquisa);

                //Adicionando os dados inseridos:
                ps.setString(1, num_acesso);

                //Execução da busca:
                rs = ps.executeQuery();

                //Verificando se o registro existe:
                if(rs.next())
                {
                    //Armazenando o id (chave-primária) do registro:
                    int realId = rs.getInt("id_usuario");

                    //Inserindo o comando sql que será executado:
                    sql = "UPDATE usuario set situacao='" + situacao + "' where id_usuario = " + realId;
                    //Inserindo a descrição da ação sql
                    msg = "Reativação de registro";
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Não é possível alterar um registro não existente! ", "Mensagem do Programa", JOptionPane.ERROR_MESSAGE);
                }
                //Executando comando sql:
                ps.executeUpdate(sql);
                //Informando que a ação foi realizada:
                JOptionPane.showMessageDialog(null, msg + " realizada com sucesso!!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
                
                //Atualizando tabela dos condomínios inativados:
                ps = con.prepareStatement("SELECT usuario.nome, usuario.num_acesso, usuario.senha, porteiro.turno " +
                    "FROM porteiro " +
                    "INNER JOIN usuario ON porteiro.id_usuario = usuario.id_usuario " +
                    "WHERE usuario.situacao = 'inativo' AND porteiro.id_condominio = ? " +
                    "ORDER BY id_condominio");
                
                ps.setInt(1, id_cond);    
                rs = ps.executeQuery();
                rs.first();
                preencherTabela();
                //Desativando botão, pois o usuário só pode utilizá-lo ao selecionar um registro:
                btn_Reativar.setEnabled(false);
            }
            catch(SQLException errosql)
            {
                JOptionPane.showMessageDialog(null, "\n Erro na gravação: \n " + errosql, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
            }
        } 
        
    }//GEN-LAST:event_btn_ReativarActionPerformed

    private void logo(){
        ImageIcon imageIcon = new ImageIcon(getClass().getResource("/img/logo/SRs.png"));
        Image scaleImage = imageIcon.getImage().getScaledInstance(170, 170,Image.SCALE_DEFAULT);
        ImageIcon img = new ImageIcon(scaleImage);
        lblLogo.setIcon(img);
    }
    
    //Esse método chama os componentes da tabela do banco, e os coloca no jtable:
    private void preencherTabela(){
        tbl_port_inativados.getColumnModel().getColumn(0).setPreferredWidth(120);
        tbl_port_inativados.getColumnModel().getColumn(1).setPreferredWidth(60);
        tbl_port_inativados.getColumnModel().getColumn(2).setPreferredWidth(60);
        tbl_port_inativados.getColumnModel().getColumn(3).setPreferredWidth(60);
        
        DefaultTableModel modelo = (DefaultTableModel) tbl_port_inativados.getModel();
        modelo.setNumRows(0);
        
        try 
        {
            rs.beforeFirst();
            while(rs.next())
            {
                modelo.addRow
                (
                        new Object[]
                        {
                            rs.getString("nome"), rs.getString("num_acesso"), rs.getString("senha"), rs.getString("turno")
                        }
                );
            }
        }
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(null,"\n Erro ao listar dados da tabela!! \n " + erro,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel back1;
    private javax.swing.JPanel back2;
    private javax.swing.JPanel back3;
    private javax.swing.JButton btn_Reativar;
    private javax.swing.JButton btn_cond_in;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_gerenc_cond;
    private javax.swing.JButton btn_gerenc_port;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_port_in;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lbl_Titulo;
    private javax.swing.JLabel lbl_desc;
    private javax.swing.JTable tbl_port_inativados;
    // End of variables declaration//GEN-END:variables
}
