/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package porteiro;

import java.awt.Image;
import javax.swing.ImageIcon;
import admin.frm_pre_gporteiros;
import conexao.Conexao;
import controle.login;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author werlang
 */
public class frm_gerenc_entrada extends javax.swing.JFrame {

    //Objeto com atributos da classe Connection. Finalidade: Ligação com Banco de Dados.
    Connection con = null;
    
    //Objeto com atributos da classe ResultSet. Finalidade: Procura dos registros do banco.
    ResultSet rs = null;
    
    /*Objeto com atributos da classe PreparedStatement. 
    Finalidade: Adicionar os dados inseridos pelo usuário na busca de dados do banco.*/
    PreparedStatement ps = null;
    
    //Atributos utilizados para passagem de parâmetro e comparação de dados:
    private int id_cond;
    private int id_user;
    
    /**
     * Creates new form frm_gerenc_entrada
     */
    public frm_gerenc_entrada(int realCond, int realIdUser) {
        initComponents();
        initVars(realCond, realIdUser);
        con = Conexao.conecta();
        logo();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        try 
        {
            String pesquisa = "SELECT entrada.*, veiculos.placa_veiculo, DATE_FORMAT(entrada.data_entrada, '%d-%m-%Y') AS data_formatada " +
            "FROM usuario " +
            "INNER JOIN porteiro ON usuario.id_usuario = porteiro.id_usuario " +
            "INNER JOIN condominio ON porteiro.id_condominio = condominio.id_condominio " +
            "INNER JOIN morador ON condominio.id_condominio = morador.id_condominio " +
            "INNER JOIN veiculos ON morador.num_registro = veiculos.num_registro " +
            "INNER JOIN entrada ON veiculos.id_veiculos = entrada.id_veiculos " +
            "WHERE porteiro.id_usuario = ?"; // Usando um parâmetro
            
            ps = con.prepareStatement(pesquisa);
            ps.setInt(1, id_user);
            rs = ps.executeQuery();
        } 
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(null, "Dados não localizados!" + ex, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
        preencherTabela();
    }

    //Método initVars() responsável por passar parâmetros de dados do usuário e
    //adicioná-los em atributos locais (da classe):
    private void initVars(int realCond, int realIdUser)
    {        
        id_cond = realCond;
        id_user = realIdUser;
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datac = new datechooser.DateChooser();
        back1 = new javax.swing.JPanel();
        back2 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btn_home = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        back3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_entrada = new javax.swing.JTable();
        tfDatPesq = new javax.swing.JTextField();
        btn_gerenc_mor = new javax.swing.JButton();
        btn_gerenc_vei = new javax.swing.JButton();
        btn_gerenc_entr = new javax.swing.JButton();

        datac.setForeground(new java.awt.Color(0, 53, 143));
        datac.setTextRefernce(tfDatPesq);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        back1.setBackground(new java.awt.Color(11, 25, 49));

        back2.setBackground(new java.awt.Color(11, 25, 49));

        btn_home.setBackground(new java.awt.Color(51, 121, 241));
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button/home.png"))); // NOI18N
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        btn_exit.setBackground(new java.awt.Color(51, 121, 241));
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button/exit.png"))); // NOI18N
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout back2Layout = new javax.swing.GroupLayout(back2);
        back2.setLayout(back2Layout);
        back2Layout.setHorizontalGroup(
            back2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(back2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        back2Layout.setVerticalGroup(
            back2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(back2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(back2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(back2Layout.createSequentialGroup()
                        .addGap(0, 147, Short.MAX_VALUE)
                        .addGroup(back2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        back3.setBackground(new java.awt.Color(212, 223, 253));

        tbl_entrada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Placa do Veículo", "Data", "Hora"
            }
        ));
        tbl_entrada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbl_entradaFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_entrada);

        tfDatPesq.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tfDatPesq.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDatPesqFocusGained(evt);
            }
        });

        javax.swing.GroupLayout back3Layout = new javax.swing.GroupLayout(back3);
        back3.setLayout(back3Layout);
        back3Layout.setHorizontalGroup(
            back3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(back3Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(back3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(back3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(back3Layout.createSequentialGroup()
                        .addComponent(tfDatPesq, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                        .addGap(532, 532, 532))))
        );
        back3Layout.setVerticalGroup(
            back3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, back3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(tfDatPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addGap(41, 41, 41))
        );

        btn_gerenc_mor.setBackground(new java.awt.Color(51, 121, 241));
        btn_gerenc_mor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_gerenc_mor.setForeground(new java.awt.Color(255, 255, 255));
        btn_gerenc_mor.setText("<html>  \n<center>  \nGerenciamento <br/> dos Moradores\n</center> \n</html>");
        btn_gerenc_mor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gerenc_morActionPerformed(evt);
            }
        });

        btn_gerenc_vei.setBackground(new java.awt.Color(51, 121, 241));
        btn_gerenc_vei.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_gerenc_vei.setForeground(new java.awt.Color(255, 255, 255));
        btn_gerenc_vei.setText("<html>  \n<center>  \nGerenciamento <br/> de Veículos\n</center> \n</html>");
        btn_gerenc_vei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gerenc_veiActionPerformed(evt);
            }
        });

        btn_gerenc_entr.setBackground(new java.awt.Color(0, 53, 143));
        btn_gerenc_entr.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_gerenc_entr.setForeground(new java.awt.Color(255, 255, 255));
        btn_gerenc_entr.setText("<html> \n<center> \nRegistro <br/> de Entrada\n</center>\n</html>");
        btn_gerenc_entr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gerenc_entrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout back1Layout = new javax.swing.GroupLayout(back1);
        back1.setLayout(back1Layout);
        back1Layout.setHorizontalGroup(
            back1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, back1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(back1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_gerenc_mor, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_gerenc_vei, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_gerenc_entr, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(back3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        back1Layout.setVerticalGroup(
            back1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(back1Layout.createSequentialGroup()
                .addComponent(back2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(back1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(back1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(back3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(back1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btn_gerenc_mor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btn_gerenc_vei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btn_gerenc_entr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_gerenc_morActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gerenc_morActionPerformed
        try 
        {
            //Comando SQL
            String pesquisa = "SELECT porteiro.id_condominio, usuario.id_usuario " +
                              "FROM porteiro " +
                              "INNER JOIN usuario ON porteiro.id_usuario = usuario.id_usuario " +
                              "WHERE usuario.id_usuario = ?"; // Usando um parâmetro

            /*Comando que "prepara" declaração para busca no banco, onde os dados 
            inseridos serão colocados no lugar do '?' de cada campo do select*/
            ps = con.prepareStatement(pesquisa);
            
            //Adicionando os dados inseridos ao parâmetro:
            ps.setInt(1, id_user);

            //Execução da busca:
            rs = ps.executeQuery();

            //Validando o registro do porteiro:
            if(rs.next()) {
                /*Chamando alguns atributos da tabela do banco para a passagem de 
                parâmetro e indo para tela de gerenciamento de moradores:*/
                int realCond = rs.getInt("id_condominio");
                int realIdUser = rs.getInt("id_usuario");
                
                //Acessando a interface de gerenciamento de moradores:
                frm_gerenc_moradores mostra = new frm_gerenc_moradores(realCond, realIdUser);
                mostra.setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Identificação de Condomínio falhou, por favor, consulte a empresa para mais detalhes!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
            }
        } 
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(null, "Dados não localizados!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_gerenc_morActionPerformed

    private void btn_gerenc_entrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gerenc_entrActionPerformed
    try 
        {
            //Comando SQL
            String pesquisa = "SELECT porteiro.id_condominio, usuario.id_usuario " +
                              "FROM entrada " +
                              "INNER JOIN veiculos ON entrada.id_veiculos = veiculos.id_veiculos " +
                              "INNER JOIN morador ON veiculos.num_registro = morador.num_registro " +
                              "INNER JOIN condominio ON morador.id_condominio = condominio.id_condominio " +
                              "INNER JOIN porteiro ON condominio.id_condominio = porteiro.id_condominio " +
                              "INNER JOIN usuario ON porteiro.id_usuario = usuario.id_usuario " +
                              "WHERE usuario.id_usuario = ?"; // Usando um parâmetro

            /*Comando que "prepara" declaração para busca no banco, onde os dados 
            inseridos serão colocados no lugar do '?' de cada campo do select*/
            ps = con.prepareStatement(pesquisa);
            
            //Adicionando os dados inseridos ao parâmetro:
            ps.setInt(1, id_user);

            //Execução da busca:
            rs = ps.executeQuery();

            //Validando o registro do porteiro:
            if(rs.next()) 
            {
                /*Chamando alguns atributos da tabela do banco para a passagem de 
                parâmetro e indo para tela de gerenciamento de moradores:*/
                int realCond = rs.getInt("id_condominio");
                int realIdUser = rs.getInt("id_usuario");     
                
                //Acessando a interface de gerenciamento de entrada:
                frm_gerenc_entrada mostra = new frm_gerenc_entrada(realCond, realIdUser);
                mostra.setVisible(true);
                dispose();
                
            } 
            else 
            {
                JOptionPane.showMessageDialog(null, "Identificação de Condomínio falhou, por favor, consulte a empresa para mais detalhes!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
            }
            
        } 
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(null, "Dados não localizados!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_gerenc_entrActionPerformed

    private void btn_gerenc_veiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gerenc_veiActionPerformed
        try 
        {
            //Comando SQL
            String pesquisa = "SELECT porteiro.id_condominio, usuario.id_usuario " +
                              "FROM veiculos " +
                              "INNER JOIN morador ON veiculos.num_registro = morador.num_registro " +
                              "INNER JOIN condominio ON morador.id_condominio = condominio.id_condominio " +
                              "INNER JOIN porteiro ON condominio.id_condominio = porteiro.id_condominio " +
                              "INNER JOIN usuario ON porteiro.id_usuario = usuario.id_usuario " +
                              "WHERE usuario.id_usuario = ?"; // Usando um parâmetro

            /*Comando que "prepara" declaração para busca no banco, onde os dados 
            inseridos serão colocados no lugar do '?' de cada campo do select*/
            ps = con.prepareStatement(pesquisa);
            
            //Adicionando os dados inseridos ao parâmetro:
            ps.setInt(1, id_user);

            //Execução da busca:
            rs = ps.executeQuery();

            //Validando o registro do porteiro:
            if(rs.next()) {
                /*Chamando alguns atributos da tabela do banco para a passagem de 
                parâmetro e indo para tela de gerenciamento de moradores:*/
                int realCond = rs.getInt("id_condominio");
                int realIdUser = rs.getInt("id_usuario");
                
                //Acessando a interface de gerenciamento de moradores:
                frm_gerenc_veiculos mostra = new frm_gerenc_veiculos(realCond, realIdUser);
                mostra.setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Identificação de Condomínio falhou, por favor, consulte a empresa para mais detalhes!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
            }
        } 
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(null, "Dados não localizados!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }        
    }//GEN-LAST:event_btn_gerenc_veiActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        login mostra = new login();
        mostra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void tfDatPesqFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDatPesqFocusGained
        tfDatPesq.enable(true);
        String data_entrada = tfDatPesq.getText();

        try {
            // Converter a data de entrada do formato "dd/MM/yyyy" para o formato padrão do MySQL "yyyy-MM-dd"
            SimpleDateFormat inputDateFormat = new SimpleDateFormat("dd-MM-yyyy");
            SimpleDateFormat outputDateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date parsedDate = inputDateFormat.parse(data_entrada);
            String data_entrada_formatada = outputDateFormat.format(parsedDate);

            String filtrarEntrada = "SELECT DISTINCT entrada.*, veiculos.placa_veiculo " +
            "FROM usuario " +
            "INNER JOIN porteiro ON usuario.id_usuario = porteiro.id_usuario " +
            "INNER JOIN condominio ON porteiro.id_condominio = condominio.id_condominio " +
            "INNER JOIN morador ON condominio.id_condominio = morador.id_condominio " +
            "INNER JOIN veiculos ON morador.num_registro = veiculos.num_registro " +
            "INNER JOIN entrada ON veiculos.id_veiculos = entrada.id_veiculos " +
            "WHERE entrada.data_entrada = ?";
            //condominio.id_condominio = ? AND 
            ps = con.prepareStatement(filtrarEntrada);
            //ps.setInt(1, id_cond);
            ps.setString(1, data_entrada_formatada); // Usar a data formatada
            
            rs = ps.executeQuery();
            rs.first();
            preencherTabela();
            tbl_entradaFocusGained(evt);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível listar os dados requisitados!" + ex, "Mensagem do Programa", JOptionPane.ERROR_MESSAGE);
            tbl_entradaFocusGained(evt);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível listar os dados requisitados!" + ex, "Mensagem do Programa", JOptionPane.ERROR_MESSAGE);
            tbl_entradaFocusGained(evt);
        }
    }//GEN-LAST:event_tfDatPesqFocusGained

    private void tbl_entradaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbl_entradaFocusGained
        tfDatPesq.enable(false);
        tfDatPesq.enable(true);
    }//GEN-LAST:event_tbl_entradaFocusGained

    private void logo(){
            ImageIcon imageIcon = new ImageIcon(getClass().getResource("/img/logo/SRs.png"));
            Image scaleImage = imageIcon.getImage().getScaledInstance(170, 170,Image.SCALE_DEFAULT);
            ImageIcon img = new ImageIcon(scaleImage);
            lblLogo.setIcon(img);
    }

    //Esse método chama os componentes da tabela do banco, e os colocam no jtable:
    private void preencherTabela(){
        tbl_entrada.getColumnModel().getColumn(0).setPreferredWidth(120);
        tbl_entrada.getColumnModel().getColumn(1).setPreferredWidth(60);
        tbl_entrada.getColumnModel().getColumn(2).setPreferredWidth(60);
        
        DefaultTableModel modelo = (DefaultTableModel) tbl_entrada.getModel();
        modelo.setNumRows(0);
        
        try 
        {
            rs.beforeFirst();
            while(rs.next())
            {
                modelo.addRow
                (
                        new Object[]
                        {
                            rs.getString("placa_veiculo"), rs.getDate("data_entrada"), rs.getTime("hora_entrada")
                        }
                );
            }
        }
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(null,"\n Erro ao listar dados da tabela!!\n " + erro,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }

    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel back1;
    private javax.swing.JPanel back2;
    private javax.swing.JPanel back3;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_gerenc_entr;
    private javax.swing.JButton btn_gerenc_mor;
    private javax.swing.JButton btn_gerenc_vei;
    private javax.swing.JButton btn_home;
    private datechooser.DateChooser datac;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JTable tbl_entrada;
    private javax.swing.JTextField tfDatPesq;
    // End of variables declaration//GEN-END:variables
}
